version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongo-db

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - ./Modelfile:/Modelfile
  #     - ollama_models:/root/.ollama
  #   entrypoint: [
  #     "/bin/sh", "-c", "
  #     ollama serve &
  #     tail -f /dev/null
  #     "]

volumes:
  mongodata:
    driver: local
  ollama_models:
    driver: local
