version: '3'
services:
    mongo-db:
      ports:
        - 27017:27017
      image: mongo
      restart: always
      environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
      volumes:
        - mongodata:/data/db
    
    gollama:
      ports:
        - 8080:8080
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        MONGO_URI: mongodb://root:example@mongo-db:27017/
      depends_on:
        - mongo-db
        - mongo-express
    
    mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
      restart: unless-stopped
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_SERVER: mongo-db
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: password123
      depends_on:
        - mongo-db


volumes:
  mongodata:
    driver: local