POST http://localhost:8080/user/signup
Content-Type: "application/json"

{
	"FirstName":"Farmaan",
	"LastName":"Malik",
	"Email":"farmaanmalik123@gmail.com",
	"Username":"Farmaan",
	"Password":"Farmaan1234"
}
